# Generated by Django 6.0.2 on 2026-04-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_catalog', '0002_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=512)),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_catalog.film')),
            ],
        ),
    ]
