# Generated by Django 6.0.2 on 2026-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_catalog', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Ваш никнейм'),
        ),
    ]
